apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
      - name: database-container
        image: postgres:11
        ports:
        - containerPort: 5432
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: database
              key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  selector:
    app: database-pod
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  type: LoadBalancer